name: Build
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node  
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Install and Test
      run: |
        yarn install
        yarn test
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{channel:github-actions-build, text: Hello}'
